"""Add LoginRiskEvent table

Revision ID: 6b2f7660ff11
Revises: 962d0393b0ee
Create Date: 2026-06-26 17:31:27.707537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2f7660ff11'
down_revision: Union[str, None] = '962d0393b0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_risk_events_id'), 'login_risk_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_risk_events_id'), table_name='login_risk_events')
    op.drop_table('login_risk_events')
    # ### end Alembic commands ###
